### ISSUE TITLE
Batch process issue and PR labels

### ISSUE THREAD

**Issue by lfolco** [TheMagentoAssociation/magento-forger#25]
We need to update the issue labels according to this spreadsheet: https://docs.google.com/spreadsheets/d/1h6oc6khHkBVBdF20r8FWB3HdIVHm6RJq2OjxZSphBUw/edit?usp=sharing.

The spreadsheet has two tabs: one for labels with the _Area_ prefix, one for labels with the _Component_ prefix.

There are columns with the label text, description (can be ignored for now), _Keep?_ and _Replace With_. If a label is marked as _No_ for _Keep?_, then any associated issues and PRs should be replaced using the label in _Replace With_.  If a label is is empty under _Keep?_, but has a value in _Rename_, then rename the existing label. There is no need to do anything with it's associated issues/PRs.

At the bottom of each spreadsheet tab is a list of new labels; these should be added first.

This should be written as a one-time CLI that reads a spreadsheet. Do the new labels first, then the renames, then finally the remapping/removing.

Write tests to ensure that we don't delete anything that we shouldn't delete.

**Comment by lfolco** [comment]
@nithinterrific I just merged a bunch of PRs, please check the main branch.

**Comment by pandiselvamtm** [comment]
Scenarios: 
1) Creating a new label 
2) Renaming a new label 
3) Switching / Remap  Label - from one (Area: Design/Frontend) to another one (Area: Frontend) instead of renaming, if not exists it will create a label here

**Comment by lfolco** [comment]
@nithinterrific can you guys open a draft PR for this?

**Comment by lfolco** [comment]
@nithinterrific can you give me an update on this? Or open a PR?

**Comment by nithinterrific** [comment]
Hello @lfolco I was away, As I was attending the worldef conference last week. We tried to push the branch from local and was not able to do so due to permission issues. Could you please provide relevant access to the github id pandiselvamtm

**Comment by lfolco** [comment]
Done

**Comment by pandiselvamtm** [comment]
> Done

Hi @lfolco , I had tried to push the changes still failing due to permission issue

<img width="458" height="185" alt="Image" src="https://github.com/user-attachments/assets/69ca3718-9323-4809-9c51-595c62a85cc3" />

Thanks!

**Comment by lfolco** [comment]
@pandiselvamtm you need to accept the invitation:

<img width="548" height="174" alt="Image" src="https://github.com/user-attachments/assets/381d90b7-81a5-4757-8b8e-c56298b013dd" />

**Comment by lfolco** [comment]
turns out we don't have the permissions to do this, closing.
